taxi_project/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('index_page', views.index_page, name='index_page'),
    path('drivers', views.drivers_page, name='drivers_page'),
    path('drivers_application', views.drivers_application_page, name='drivers_application_page'),
    path('passengers', views.passengers_page, name='passengers_page'),
    path('helpdesk', views.helpdesk_page, name='helpdesk_page'),
    path('register', views.register_page, name='register_page'),
    path('login', views.login_page, name='login_page'),
    path('logout', views.logout_view, name='logout_view'),
    path('profile', views.profile_page, name='profile_page'),
    path('profile/delete', views.profile_delete_view, name='delete_profile'),

]

taxi_project/manager/urls.py
from django.urls import path
from main import views as main_views

app_name = 'manager'

urlpatterns = [
    path('profile', main_views.profile_page, name='profile_page'),
]

taxi_project/taxi_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('main/', include('main.urls')),
    path('manager/', include('manager.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taxi_project/main/models.py
from django.db import models

# Данные водителя и его автомобиля доступные для суперАдмина

class Driver(models.Model):
    name = models.CharField(max_length=100, verbose_name='ФИО водителя')
    identification_card = models.IntegerField(verbose_name='Удостоверение личности, №')
    driver_license = models.IntegerField(verbose_name='Водительское удостоверение')
    car_info = models.TextField(verbose_name='Марка, модель авто, год выпуска')
    car_number = models.CharField(max_length=8, verbose_name='Государственный номер автомобиля')

    def __str__(self):
        return f"{self.name}: {self.avatar}"
    # Русификация категории пользователей для суперАдмина
    class Meta:
        verbose_name = 'Водитель'
        verbose_name_plural = 'Водители'

#  Данные пассажира доступные для суперАдмина

class Passenger(models.Model):
    name = models.CharField(max_length=100, verbose_name='ФИО пассажира')
    telephone_number = models.IntegerField(verbose_name='Номер телефона')
    email = models.EmailField(max_length=100, verbose_name='Электронная почта')

    def __str__(self):
        return self.name
  # Русификация категории пользователей для суперАдмина
    class Meta:
        verbose_name = 'Пассажир'
        verbose_name_plural = 'Пассажиры'


 #  Данные обращений доступные для суперАдмина

class Comment(models.Model):
    author = models.CharField(max_length=30, verbose_name="Автор обращения")
    comment_text = models.TextField(verbose_name="Текст обращения")
    created_date = models.DateField(auto_now_add=True, verbose_name="Дата создания обращения")
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.author}: {self.created_date - {self.passenger}}"

    # Русификация категории пользователей для суперАдмина
    class Meta:
        verbose_name = 'Обращение'
        verbose_name_plural = 'Обращения'

taxi_project/manager/models.py
from django.db import models

# Create your models here.

taxi_project/main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from . import models

# Create your views here.
def index_page(request):
    print("request is accepted")
    return render(request, "main/index.html", {})

def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username", None)
        password = request.POST.get("password", None)
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse("main:profile_page"))

        return render(request, "main/login.html", {"error": "Неправильный логин/пароль"})
    return render(request, "main/login.html", {})

def helpdesk_page(request, pk):
    comments = models.Comment.objects.get(pk=pk)

    if request.method == "GET":
        return render(request, "main/helpdesk_page.html", {"comments": comments})
    else:
        author = request.POST.get("author", None)
        comment_text = request.POST.get("comment", None)
        models.Comment.objects.create(
            author=author,
            comment_text=comment_text,
        )

        return redirect(reverse("main:helpdesk_page", args=(pk,)))

def profile_page(request):
    """
    Контроллер, отвечающий за логику:
    - отображения профиля пользователя
    - изменения данных пользователя
    Пользователь должен быть аутентифицирован
    """

    if request.user.is_authenticated:
        # изменение данных пользователя при POST запросе
        if request.method == "POST":
            password = request.POST.get("password", None)
            first_name = request.POST.get("first_name", None)
            last_name = request.POST.get("last_name", None)

            user = request.user

            if password:
                user.set_password(password)

            if first_name:
                user.first_name = first_name

            if last_name:
                user.last_name = last_name

            user.save(update_fields=['password', 'first_name', 'last_name'])

            # если было изменение пароля, значит перенаправить на страницу аутентификации
            # так как сессия должна быть пересоздана
            if password:
                return redirect(reverse("main:login_page"))

            return redirect(reverse("main:profile_page"))

        # возвратить страницу профиля при GET запросе
        return render(request, "main/profile.html", {})
    return redirect(reverse("main:login_page"))


def logout_view(request):
    logout(request)
    return redirect(reverse("main:index_page"))


def register_page(request):
    if request.method == "POST":
        try:
            # QWErty123
            username = request.POST.get("username", None)
            password = request.POST.get("password", None)
            email = request.POST.get("email", None)
            first_name = request.POST.get("first_name", None)
            last_name = request.POST.get("last_name", None)
            user = User.objects.create_user(
                username=username,
                password=password,
                email=email,
                first_name=first_name,
                last_name=last_name,
            )
            return redirect(reverse("main:login_page"))
        except Exception as exc:
            print("при создании пользователя произошла ошибка", request.POST, exc)
            error = {
                "error_code": exc,
                "message": "Проверьте корректность введенных данных"
            }
            return render(request, "main/register.html", {"error": error})

    return render(request, "main/register.html", {})


def profile_delete_view(request):
    if request.user.is_authenticated:
        try:
            user = request.user
            user.delete()
            return redirect(reverse('main:index_page'))
        except Exception as exc:
            print(f"при удалении пользователя {request.user.pk} произошла ошибка", exc)
        return redirect(reverse('main:profile_page'))

    # Если пользователь не аутентифицирован, перенаправить на страницу логина
    return redirect(reverse('main:login_page'))

def drivers_page(request):
    return render(request, "main/drivers.html", {})

def drivers_application_page(request):
    return render(request, "main/drivers_application.html", {})

def passengers_page(request):
    return render(request, "main/passengers.html", {})

def helpdesk_page(request):
    return render(request, "main/helpdesk_page.html", {})

taxi_project/manager/views.py
from django.shortcuts import render

# Create your views here.

taxi_project/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
</head>
<body class="container-fluid">
    {% include "main/header.html" %}
    {% block body %}

    {% endblock %}

    {% include "main/footer.html" %}
</body>
</html>

taxi_project/main/templates/main/drivers.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Drivers Page {% endblock %}

{% block body %}
<div class="container-fluid row bg-warning">

          <div class="container-fluid pt-2">

              <div class="row">

                  <!-- 1й раздел, 1й столбец - текст для водителей -->

                  <div class="col-sm-4 my-auto">
                      <h1 class="text-center">Работайте водителем такси в Казахстане</h1>
                      <p class="text-center">
                          став партнёром "Тұлпар taxi"
                      </p>
                  </div>

                  <!-- 1й раздел, 2й столбец - картинка -->

                      <!-- Карусель -->

                  <div id="demo" class="carousel slide col-sm-4" data-bs-ride="carousel">

                          <!-- 2 эемента для прокрутки -->

                      <div class="carousel-indicators">
                          <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                          <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                      </div>

                          <!-- Эффект слайдшоу / картинки для главной страницы -->

                      <div class="carousel-inner">
                          <div class="carousel-item active">
                              <img src="{% static 'main/drivers_page.jpg' %}" alt="#" class="rounded d-block w-100">
                          </div>
                          <div class="carousel-item">
                              <img src="{% static 'main/drivers_page_1.jpg' %}" alt="#" class="rounded d-block w-100">
                          </div>
                      </div>

                          <!-- Функция прокрутки картинок -->

                      <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon"></span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                          <span class="carousel-control-next-icon"></span>
                      </button>
                  </div>

                  <!-- 1й раздел, 3й столбец - текст по условиям -->

                  <div class="col-sm-4 my-auto">
                      <h3>Быстрый старт</h3>
                      <p>
                          От заявки до первого клиента — несколько часов
                      </p>

                      <h3>Деньги — сразу</h3>
                      <p>
                          Оплату за наличные заказы вы получите в первый день работы
                      </p>

                      <h3>Удобный график</h3>
                      <p>
                          Работайте несколько часов в день или полную смену
                      </p>
                  </div>
              </div>

              <div class="container-fluid pt-1">
                  <div class="col-sm-12 my-auto">
                      <h3>Оставляйте заявку прямо сейчас</h3>
                      <img width="100" height="100" src="{% static 'main/down_arrow.gif' %}">
                  </div>
                  <div class="row">
                      <a href="{% url 'main:login_page' %}" class="text-reset">Регистрация для водителей</a>
                  </div>
              </div>
          </div>

    </div>

{% endblock %}

taxi_project/main/templates/main/drivers_application.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Drivers Application Page {% endblock %}

{% block body %}
<div class="container-fluid row bg-warning pt-2">

      <div class="row">

          <!-- 1й раздел, 1й столбец - текст приложения для водителей + сслыка-->


          <div class="col-sm-4 my-auto">
              <h1>Скачайте наше мобильное приложение</h1>

              <a href="#" class="text-reset ">Приложение "Тұлпар taxi Pro"</a>
          </div>


          <!-- 1й раздел, 2й столбец - картинка -->

              <!-- Карусель -->

          <div id="demo" class="carousel slide col-sm-8" data-bs-ride="carousel">

                  <!-- 2 эемента для прокрутки -->

              <div class="carousel-indicators">
                  <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                  <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
              </div>

                  <!-- Эффект слайдшоу / картинки для главной страницы -->

              <div class="carousel-inner">
                  <div class="carousel-item active">
                      <img src="{% static 'main/drivers_application_page_1.jpg' %}" alt="#" class="rounded d-block w-100">
                  </div>
                  <div class="carousel-item">
                      <img src="{% static 'main/drivers_application_page_2.jpg' %}" alt="#" class="rounded d-block w-100">
                  </div>
              </div>

                  <!-- Функция прокрутки картинок -->

              <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon"></span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                  <span class="carousel-control-next-icon"></span>
              </button>
          </div>
      </div>
</div>

{% endblock %}

taxi_project/main/templates/main/footer.html
{% load static %}

<!-- Footer -->
<footer class="text-center text-lg-start bg-warning text-black">

  <!-- Раздел: Социальные сети -->

  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">

    <!-- Слева надпись -->
    <div class="me-5 d-none d-lg-block">
      <span>Свяжитесь с нами также в социальных сетях:</span>
    </div>

    <!-- Справа, значки соц.сетей -->
    <div>
      <a class="me-4 text-reset ">
        <img src="{% static 'main/facebook-logo.png' %}" alt="facebook" style="width:40px;" class="rounded-circle" >
      </a>
      <a class="me-4 text-reset">
        <img src="{% static 'main/instagram-logo.png' %}" alt="instagram" style="width:40px;" class="rounded-circle">
      </a>
      <a class="me-4 text-reset">
        <img src="{% static 'main/youtube-logo.png' %}" alt="youtube" style="width:40px;" class="rounded-circle">
      </a>
    </div>
  </section>

  <!-- Раздел: онтакты  -->

  <section class="">
    <div class="container text-center text-md-start mt-5">

      <div class="row mt-3">

        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

          <!-- Информация -->

          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Тұлпар taxi
          </h6>
          <p>
            "Тұлпар taxi" надежная служба такси в Алматы и Алматинской Области. Мы оказываем транспортные услуги, которые сделают Вашу поездку еще более комфортной.
          </p>
        </div>

        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Ссылки 1 -->
          <h6 class="text-uppercase fw-bold mb-4">
            Пользователям
          </h6>
          <p>
            <a href="{% url 'main:passengers_page' %}" class="text-reset">Скачать приложение</a>
          </p>
          <p>
            <a href="{% url 'main:helpdesk_page' %}" class="text-reset">Написать в поддержку</a>
          </p>
          <p>
            <a href="{% url 'main:index_page' %}" class="text-reset">Заказать машину</a>
          </p>
        </div>

        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Ссылки 2 -->
          <h6 class="text-uppercase fw-bold mb-4">
            Водителям
          </h6>
          <p>
            <a href="{% url 'main:drivers_page' %}" class="text-reset">Стать водителем</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Скачать приложение для водителей</a>
          </p>
        </div>

        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

          <!-- Адрес, номер, почта -->

          <h6 class="text-uppercase fw-bold mb-4">
            Контакты
          </h6>
          <p><i class="fas fa-home me-3"></i> Алматы, ул. Абая, 77</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            tulpar-taxi@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 7 701 077 07 07</p>
          <p><i class="fas fa-print me-3"></i> + 7 777 077 07 07</p>
        </div>

      </div>

    </div>
  </section>

  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 ТОО "ТҰЛПАР":
    <a class="text-reset fw-bold" href="{% url 'main:index_page' %}">tulpar-taxi@gmail.com</a>
  </div>

</footer>
<!-- Footer -->

taxi_project/main/templates/main/header.html
{% load static %}

<header>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">

      <!-- Логотип -->

      <a class="navbar-brand" href="#">
          <img src="{% static 'main/taxi_logo.png' %}" alt="#" style="width:80px;" class="rounded-circle">
      </a>

      <!-- Главная страница с ссылкой -->

      <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:index_page' %}">Главная страница</a>
              </li>

              <!-- Раздел для водителей с выпадающим списком с ссылками -->

              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Водителям</a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'main:drivers_page' %}">Стать водителем</a></li>
                          <li><a class="dropdown-item" href="{% url 'main:drivers_application_page' %}">Скачать приложение для водителей</a></li>
                      </ul>
              </li>

             <!-- Раздел для пользователей с выпадающим списком с ссылками -->

              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Пользователям</a>
                      <ul class="dropdown-menu dropdown-menu-end">
                          <li><a class="dropdown-item" href="{% url 'main:passengers_page' %}">Скачать приложение</a></li>
                          <li><a class="dropdown-item" href="{% url 'main:helpdesk_page' %}">Написать в поддержку</a></li>
                          <li><a class="dropdown-item" href="{% url 'main:index_page' %}">Заказать машину</a></li>
                      </ul>
              </li>
          </ul>
      </div>

      <div>

          <!-- Авторизация -->

      <ul class="navbar-nav me-auto">
          {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:profile_page' %}">Профиль</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:logout_view' %}">Выход</a>
              </li>
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:login_page' %}" >Вход</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:register_page' %}">Авторизация</a>
              </li>
          {% endif %}
      </ul>



    </div>


  </div>
</nav>



</header>

taxi_project/main/templates/main/helpdesk_page.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Helpdesk Page {% endblock %}

{% block body %}
<div class="container-fluid row bg-warning">
    <div class="container-fluid pt-2">
         <div class="row">

             <!-- 1й столбец - обращения и комментарии -->

             <div class="col-sm-6 my-auto">
                 <form method="post">
                     {% csrf_token %}
                     <input type="text" name="author" placeholder="Автор обращения">
                 </form>
                 <form method="post">
                     {% csrf_token %}
                     <input type="text" name="comment" placeholder="Текст обращения">
                 </form>
                 <form method="post">
                     {% csrf_token %}
                     <input type="submit" class="btn btn-primary" value="Отправить обращение">
                 </form>
                 <ul>
                     {% for comment in comments %}
                     <li>{{ comment.author}}: {{ comment.created_date }}<br>
                         {{ comment.comment_text }}</li>
                     {% endfor %}
                 </ul>
             </div>

             <!-- 2й столбец - картинки -->

             <!-- Карусель -->

             <div id="demo" class="carousel slide col-sm-6" data-bs-ride="carousel">

                  <!-- 2 эемента для прокрутки -->

                  <div class="carousel-indicators">
                      <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                      <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                  </div>

                  <!-- Эффект слайдшоу / картинки для главной страницы -->

                  <div class="carousel-inner">
                      <div class="carousel-item active">
                          <img src="{% static 'main/helpdesk_page.jpg' %}" alt="#" class="rounded d-block w-100">
                      </div>
                      <div class="carousel-item">
                          <img src="{% static 'main/helpdesk_page_1.jpg' %}" alt="#" class="rounded d-block w-100">
                      </div>
                  </div>

                  <!-- Функция прокрутки картинок -->

                  <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon"></span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                      <span class="carousel-control-next-icon"></span>
                  </button>
             </div>
         </div>
    </div>
</div>



{% endblock %}

taxi_project/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Index Page Title {% endblock %}

{% block body %}
<div class="container-fluid row bg-warning">

      <div class="container-fluid pt-2">

          <!-- 1й раздел, 1й столбец - картинки главной страницы -->

            <div class="row bg-warning">

                <div class="col-sm-8">

                      <!-- Карусель -->

                    <div id="demo" class="carousel slide" data-bs-ride="carousel">

                      <!-- 3 эемента для прокрутки -->

                        <div class="carousel-indicators">
                            <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                            <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                            <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
                        </div>

                       <!-- Эффект слайдшоу / картинки для главной страницы -->

                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="{% static 'main/Index_page_4.jpg' %}" alt="#" class="rounded d-block w-100">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'main/Index_page_2.jpg' %}" alt="#" class="rounded d-block w-100">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'main/Index_page_3.jpg' %}" alt="#" class="rounded d-block w-100">
                            </div>
                        </div>

                        <!-- Функция прокрутки картинок -->

                        <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon"></span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                            <span class="carousel-control-next-icon"></span>
                        </button>
                    </div>

                </div>

                <!-- 1й раздел, 2й столбец - вступительный текст -->

                <div class="col-sm-4 my-auto">
                    <div class="my-auto">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">
                            Вызов такси
                        </button>

                            <!-- Всплывающее окно с номерами телефонов -->

                        <div class="modal" id="myModal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Вызов такси</h4>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12 text-center">
                                            <h3>+ 7 701 077 07 07</h3>
                                            <h3>+ 7 777 077 07 07</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="text center fw-bold pt-3">
                        "Тұлпар taxi" надежная служба такси в Алматы и Алматинской Области. Мы оказываем транспортные услуги, которые сделают Вашу поездку еще более комфортной. Все автомобили содержатся в идеальной чистоте, а за рулем сидят опытные, ответственные и внимательные водители. Сообщите о своих предпочтениях в поездке диспетчеру при заказе такси Алматы, и мы учтем все ваши пожелания.
                    </p>

                </div>
            </div>

              <!-- 2й раздел - карта города Алматы и Алматинской области -->

            <div class="row bg-warning">

                <div class="col-sm-12">
                    <div id="container"></div>
                    <script src="https://mapgl.2gis.com/api/js/v1"></script>
                    <script>
                        const map = new mapgl.Map('container', {
                            center: [76.92925, 43.24165],
                            zoom: 13,
                            key: 'Your API access key',
                        });
                        const marker = new mapgl.Marker(map, {
                            coordinates: [76.92925, 43.24165],
                        });
                    </script>
                </div>
            </div>
      </div>
</div>




{% endblock %}

taxi_project/main/templates/main/login.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Login Page {% endblock %}

{% block body %}
<div class="bg-warning">
    <div class="row">
        <div class="col-sm-12 text-center">
            <h3>Вход</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <form method="post" class="form mx-auto">
                {% if error %}
                    <p class="text-danger">{{ error }}</p>
                {% endif %}
                {% csrf_token %}
                <input type="text" class="form-control w-25" placeholder="Имя пользователя" name="username" required>
                <input type="password" class="form-control w-25" placeholder="Пароль" name="password" required>
                <input type="submit" class="btn btn-primary" value="Войти">
            </form>
        </div>
        <div class="col-sm-8">
            <img class="w-100" src="{% static 'main/login_page.jpg' %}">
        </div>
    </div>
</div>
{% endblock %}

taxi_project/main/templates/main/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Index Page Title {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
          <h2>ФИ: {{ user.last_name }} {{ user.first_name }}</h2>
          <p>Почта: {{ user.email }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 mx-auto">
                <form method="post" class="form mx-auto">
                    {% if error %}
                        <p class="text-danger">{{ error.message }}</p>
                    {% endif %}
                    {% csrf_token %}
                    <input type="password" class="form-control w-25" placeholder="Пароль" name="password">
                    <input type="text" class="form-control w-25" placeholder="Фамилия" name="last_name">
                    <input type="text" class="form-control w-25" placeholder="Имя" name="first_name">
                    <input type="submit" class="btn btn-primary" value="Изменить данные">
                </form>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 mx-auto">
            <a href="{% url 'main:delete_profile' %}">Удалить страницу</a>
        </div>
    </div>



{% endblock %}